### ISSUE TITLE
The example app does not show system tray menu on macOS.

### ISSUE THREAD

**Issue by tomoyuki28jp** [antler119/system_tray#13]
Clicking a tray menu icon triggers the event handler with eventName = "leftMouseUp", but  does not show system tray menu. (I might misunderstanding something.)

It occurs on:
- MacBook Pro Intel Core i7
- macOS 11.0.1
- Flutter 2.5.1

**Comment by antler119** [comment]
pls try v0.0.9

**Comment by tomoyuki28jp** [comment]
@antler119 I've tried v0.0.9, but it still does not show system tray menu on my mac.

**Comment by tomoyuki28jp** [comment]
Here is the screen record video.

https://user-images.githubusercontent.com/42951/152625851-3f9f5b17-edff-4aaa-8989-d0db010a78db.mov

**Comment by tomoyuki28jp** [comment]
Sorry, it's been working fine. After changing the example app to call ` _systemTray.popUpContextMenu();` on leftMouseDown/Up, it works as I expected.
