### ISSUE TITLE
api of version 0.0.7 is not the same as the source code from github

### ISSUE THREAD

**Issue by jkouubb** [antler119/system_tray#19]
Hello, I found your plugin in pub so I want to have a try. But I can not run my code with issue #3 . To find what is going wrong, I cloned source code from github and run example, it works. So I compared code from pub with the one from github, I found there is some difference between them. For example, class AppWindows is not exposed in pub but exposed in github. The first parameter "title" of member function "initSystemTray" is normal in pub but named in github.

I think issue #3 might be solved but you have not updated the code, would you please have a look?

**Comment by antler119** [comment]
try v0.0.8
