### ISSUE TITLE
Show window on tray click (no menu)

### ISSUE THREAD

**Issue by Nealsoni00** [antler119/system_tray#4]
Hey! Very useful plugin! -- I just wanted to see if there is a way to show the app directly when they press the tray icon? I ideally would want to show the menu options when they right-click the tray icon.

**Comment by DevJHenrique** [comment]
Use this

```
_systemTray.registerSystemTrayEventHandler((eventName) {
      print("eventName: $eventName");
      if (eventName == 'leftMouseUp') {
        appWindow.show();
      }
    });
```

**Comment by wess** [comment]
How would you suggest positioning the window right under the systray icon?

**Comment by bigfish258** [comment]
@DevJHenrique  hello,  i use your code , it open the window one time , then the app closed.  
here is the error , pls help :  
`	24  HIToolbox                           0x00007fff2885a583 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	25  AppKit                              0x00007fff22e1c502 _DPSNextEvent + 864
	26  AppKit                              0x00007fff22e1acd5 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
	27  AppKit                              0x00007fff22e0d049 -[NSApplication run] + 586
	28  AppKit                              0x00007fff22de124c NSApplicationMain + 816
	29  macpic813                           0x0000000107dc323d main + 13
	30  libdyld.dylib                       0x00007fff20539f3d start + 1
	31  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi: terminating with uncaught exception of type NSException
Lost connection to device
`
