### ISSUE TITLE
Running Flutter app in release / compiled mode doesn't always show the icon in the system tray

### ISSUE THREAD

**Issue by Kevin-McKee** [antler119/system_tray#44]
I have downloaded the repository and have run the example app.  In debug, the system tray icon seems to always appear, but when I run in release mode, or do a "flutter build windows" and run the resulting executable, sometimes the icon shows, other times not - even though I do see the .exe process running in the task manager.  Is there any way to troubleshoot/debug what's happening in the instances where the icon doesn't show?

I'm running version ^0.1.1 on Windows 10, Flutter 3.0.1

**Comment by Kevin-McKee** [comment]
I think I found the issue, where I had not packed up all of the required files to go along with the release version.

**Comment by nickcuypers** [comment]
@Kevin-McKee  can you explain a little more because I'm facing the same issue

**Comment by Kevin-McKee** [comment]
> @Kevin-McKee can you explain a little more because I'm facing the same issue

I wish I could recall but it's escaping me at the moment.  I do remember at one point (whether it was with this issue or something else), I had tried to use .png files for the tray icon but it wouldn't show.  I figured out that you have to use .ico files.  If I eventually remember I will certainly get back to you

**Comment by nickcuypers** [comment]
@Kevin-McKee I'm already using .ico files but thx for the effort 👍
