### ISSUE TITLE
Adaptive Status Bar Icon

### ISSUE THREAD

**Issue by smpgallagher** [antler119/system_tray#55]
The icon doesn't change color when the status bar changes color.
In macos, you set a menuitem image from an asset to enable adaptive icons (black / white status bar toggle)
Adding a channel for the following code allows for use of the asset

 func setStatusBarImage(_ call: FlutterMethodCall, _ result: FlutterResult)
  {
    let assetName = call.arguments as? String
    if assetName != nil {
      statusItem?.button?.image = NSImage.init(named: assetName!)
    result(true)
    }
    result(false)
  }

**Comment by Narek6556** [comment]
You need to add below line
statusItem?.button?.image?.isTemplate = true

**Comment by anilcngz** [comment]
Have you found a solution to this issue? If so, could you share it with us? Thanks in advance
