### ISSUE TITLE
Failed to lookup symbol

### ISSUE THREAD

**Issue by zhuima** [antler119/system_tray#6]
[ERROR:flutter/runtime/dart_isolate.cc(1138)] Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, bitsdojo_window_api): symbol not found)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      bitsdojoWindowAPI (package:bitsdojo_window_macos/src/native_api.dart:199:6)
#2      bitsdojoWindowAPI (package:bitsdojo_window_macos/src/native_api.dart)
#3      _publicAPI (package:bitsdojo_window_macos/src/native_api.dart:202:42)
#4      _publicAPI (package:bitsdojo_window_macos/src/native_api.dart)
#5      _setWindowCanBeShown (package:bitsdojo_window_macos/src/native_api.dart:27:5)
#6      _setWindowCanBeShown (package:bitsdojo_window_macos/src/native_api.dart)
#7      setWindowCanBeShown (package:bitsdojo_window_macos/src/native_api.dart:28:41)
#8      BitsdojoWindowMacOS.doWhenWindowReady.<anonymous closure> (package:bitsdojo_window_macos/src/bitsdojo_window_macos_real.dart:14:7)
#9      _rootRunUnary (dart:async/zone.dart:1436:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>

ENV

 Flutter (Channel master, 2.5.0-6.0.pre.29, on Mac OS X 10.15.7 19H524 darwin-x64, locale zh-Hans-CN)

**Comment by antler119** [comment]
try v2.0.0
