### ISSUE TITLE
keep app open in tray when window closed

### ISSUE THREAD

**Issue by Nealsoni00** [antler119/system_tray#7]
Hey! Super useful plugin!

One value in having the tray icon is that if someone closes the window of the application (with the close button or command + q) the app will still appear in the tray and can be opened by clicking the tray icon. Is there a way to do this using the plugin?

Thanks!

**Comment by Nealsoni00** [comment]
Thanks @antler119 -- The issue is when they quit the app using a native way:
![image](https://user-images.githubusercontent.com/7013191/129045914-fe436cad-dbe1-4b25-9c07-77303a223a58.png)

Do you know of any way to prevent those from closing the window/flutter app completely and instead just hiding the window?

Thanks!

**Comment by antler119** [comment]
on window you can try this
``` 
// flutter_window.cpp
LRESULT
FlutterWindow::MessageHandler(HWND hwnd,
                              UINT const message,
                              WPARAM const wparam,
                              LPARAM const lparam) noexcept {
  // Give Flutter, including plugins, an opportunity to handle window messages.
  if (flutter_controller_) {
    std::optional<LRESULT> result =
        flutter_controller_->HandleTopLevelWindowProc(hwnd, message, wparam,
                                                      lparam);
    if (result) {
      return *result;
    }
  }

  switch (message) {
    case WM_FONTCHANGE:
      flutter_controller_->engine()->ReloadSystemFonts();
      break;
    case WM_CLOSE: // add this
      return 0; 
      break;
  }

  return Win32Window::MessageHandler(hwnd, message, wparam, lparam);
}
```

**Comment by Nealsoni00** [comment]
Amazing! instead of return 0, is there a way to explicitly hide the window?

Sorry for asking so many questions! I'm trying to migrate an app from electron to flutter

**Comment by antler119** [comment]
```
    case WM_CLOSE:
      ShowWindow(GetHandle(), SW_HIDE); // try this code
      return 0;
      break;
```

**Comment by timzaak** [comment]
How about macOS?
