### ISSUE TITLE
example won't build for linux

### ISSUE THREAD

**Issue by sgehrman** [antler119/system_tray#8]
CMake Error at /snap/flutter/91/usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /snap/flutter/91/usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  flutter/ephemeral/.plugin_symlinks/system_tray/linux/CMakeLists.txt:10 (pkg_check_modules)

**Comment by sgehrman** [comment]
I'm on Debian.  I got past the first issue, but now getting

[   +1 ms] /snap/flutter/current/usr/bin/ld: cannot find -lpkgcfg_lib_APPINDICATOR_appindicator3-NOTFOUND
[        ] /snap/flutter/current/usr/bin/ld: cannot find -lpkgcfg_lib_APPINDICATOR_dbusmenu-glib-NOTFOUND
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sgehrman** [comment]
I tried everything.  I installed every single appIndicator package and nothing works.

**Comment by antler119** [comment]
Which Linux system are you using？
You can try cmd `ldconfig -p | grep libappindicator` to show what libappindicator do you have in your system.

**Comment by sgehrman** [comment]
libappindicator3.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libappindicator3.so.1
	libappindicator3.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libappindicator3.so
	libappindicator.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libappindicator.so.1
	libappindicator.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libappindicator.so

**Comment by sgehrman** [comment]
Linux 5950x 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

**Comment by antler119** [comment]
can you try cmd `pkg-config --cflags appindicator3-0.1` or `pkg-config --cflags appindicator-0.1` to find some errors?

**Comment by sgehrman** [comment]
Hey, I decided to write my own plugin.  I didn't want the dojowindow.  And I couldn't get past those compile errors.

 I got it working in a private repo app, but the plugin is open source.  https://github.com/sgehrman/status_bar/tree/master

I need help with Windows if you happen to be a Windows guy.  I only have mac and linux.
